### ISSUE TITLE
Acciones en pesos

### ISSUE THREAD

**Issue by gb-simon** [pgPilfs/pil-money-g3b-equipo-grupo-3-b#3]
Como usuario quiero ingresar dinero para poder guardar dinero en mi billetera digital.

**Comment by Sofiazanetti** [comment]
Como usuario quiero retirar dinero para poder tener dinero disponible de manera física.

**Comment by Sofiazanetti** [comment]
Como usuario quiero poder ingresar dinero tal que pueda pagar mis cuentas

**Comment by Sofiazanetti** [comment]
Como usuario quiero consultar el dinero disponible en mi cuenta para verificar si cuento con dinero suficiente para realizar una transacción?

**Comment by Sofiazanetti** [comment]
Como usuario quiero consultar las n-ultimas operaciones realizadas en pesos para consultar los movimientos realizados en mi cuenta.

**Comment by Sofiazanetti** [comment]
Como usuario quiero poder girar dinero al descubierto de acuerdo a mi capacidad crediticia para poder obtener crédito

**Comment by Sofiazanetti** [comment]
Como usuario quiero enviar dinero a otra cuenta en pesos desde mi billetera virtual para realizar una transferencia o un pago.

**Comment by JSjuan** [comment]
> Como usuario quiero ingresar dinero para poder guardar dinero en mi billetera digital.

**Comment by JSjuan** [comment]
abri de nuevoo

**Comment by JSjuan** [comment]
Ahora si cierro
